
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'tramitaciones'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

seeds:
  tramitaciones:
    quote_columns: true
    vial_cat_clientes:
      +schema: config
      +column_types:
        cliente_id: int
        cliente: varchar(120)
        grupo_cliente: varchar(120)
        industria_id: int
        industria: varchar(50)
        aduanet_id: varchar(28)
    cat_aduanas:
      +schema: config
      +column_types:
        aduana_id: int
        aduana: varchar(100)
    vial_cat_cuentas:
      +schema: config
      +column_types:
        cuenta: int
        sub_cta: int
        subsubcta: int
        nombrecta: varchar(100)
        cta: varchar(15)
        mayor: varchar(4)
        cuenta: varchar(4)
        llave: varchar(100)
        categoria: varchar(50)
        subcategoria: varchar(50)
        orden: int
    cat_fechas:
      +schema: config
      +column_types:
        fecha: date
        habil_mx: bool
        habil_usa: bool
    cat_departamentos:
      +schema: config
      +column_types:
        departamento: varchar(20)
        grupodepartamento: varchar(20)
    encuestas:
      +schema: config
      +column_types:
        periodo: int
        pregunta_1: varchar(2)
        pregunta_2: varchar(2)
        pregunta_3: varchar(2)
        pregunta_4: varchar(2)
        pregunta_5: varchar(2)
        pregunta_6: varchar(2)
        pregunta_7: varchar(2)
        pregunta_8: varchar(2)
        pregunta_9: varchar(2)
        pregunta_10: varchar(2)
        cliente: varchar(30)
        todos: float(2)
    encuestas_enviadas:
      +schema: config
      +column_types:
        periodo: int
        encuestados: int
    balanza_comercial:
      +schema: config
      +column_types:
        periodos: varchar(12)
        import: float(2)
        export: float(2)
      
# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
    quickbooks:
      +schema: quickbooks_public # leave blank for just the target_schema
    quickbooks_source:
      +schema: quickbooks_stg # leave blank for just the target_schema

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
#models:
#  my_new_project:
    # Config indicated by + and applies to all files under models/example/
#    example:
#      +materialized: view
